# -*- coding: utf-8 -*-
"""slowy07Geocoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F17dzeBdF6I5UQWRdv4HHfiRU0MEMzmt
"""

!apt install gdal-bin python-gdal python3-gdal --quiet
!apt install python3-rtree --quiet
!pip install git+git://github.com/geopandas/geopandas.git --quiet
!pip install descartes --quiet
!pip install geopy
!pip install plotly_express
!pip install ipython-autotime

import pandas as pd
import geopandas as gpd
import geopy
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import matplotlib.pyplot as plt
import folium
from folium.plugins import FastMarkerCluster

locator = Nominatim(user_agent="myGeocoder")
location = locator.geocode("Monas, Jakarta, Indonesia")

print(location.address)
print("Latitude = {}, Longitude = {}".format(location.latitude, location.longitude))

from google.colab import files
data_to_load = files.upload()

df = pd.read_csv("dataOOF.csv")
df.head()

df['ADDRESS'] = df['Langsa'].astype(str) + ',' + \
                df['Langsa.1'] + ',' + \
                df['Langsa.2'] + ',' + \
                df['Langsa.3'] + ',' + 'Langsa'   

df.head()