# -*- coding: utf-8 -*-
"""tourTheWorld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mQEhE3i2U8VAiKVMxv5oe0VcC5DXO9ah
"""

!pip install arcgis

from arcgis import GIS
from arcgis.raster.functions import *
gis = GIS()

landsatItem = gis.content.search('"Multispectral Landsat"', 'Imagery Layer')[0]
landsatItem

landsat = landsatItem.layers[0]
def extract_stretch(bandids):
    return stretch(extract_band(landsat, bandids),
                   stretch_type='PercentClip',
                   min_percent=2, 
                   max_percent=2,
                   dra=True, 
                   gamma=[0.8,0.8,0.8])

cambridge_gulf = extract_stretch([5, 4, 1])
cambridge_gulf.extent = {'xmax': 128.96, 'xmin': 127.62, 'ymax': -14.72, 'ymin': -15.25, 'spatialReference': 4326}
cambridge_gulf

eyeOfSahara = extract_stretch([6,3,1])
eyeOfSahara.extent = {'xmax': -10.6, 'xmin': -11.94, 'ymax': 21.38, 'ymin': 20.86, 'spatialReference': 4326}
eyeOfSahara

gossesBluf = extract_stretch([6,3,1])
gossesBluf.extent = {'xmax': 133.23, 'xmin': 131.89, 'ymax': -23.7, 'ymin': -24.2, 'spatialReference': 4326}
gossesBluf

exumasBahamas = extract_stretch([5, 3, 0])
exumasBahamas.extent = {'xmax':-75.31, 'xmin':-75.98, 'ymax':23.62, 'ymin':23.37, 'spatialReference':4326}
exumasBahamas

mexicoCity = extract_stretch([6, 5, 3])
mexicoCity.extent = {'xmax': -98.76, 'xmin': -99.44, 'ymax': 19.54, 'ymin': 19.28,'spatialReference': 4326}
mexicoCity

centralSaudiArabia = extract_stretch([5, 4, 1])
centralSaudiArabia.extent = {'xmax': 45.18, 'xmin': 43.82, 'ymax': 26.0, 'ymin': 25.5, 'spatialReference': 4326}
centralSaudiArabia

bahrAlMilh = extract_stretch([5, 1, 0])
bahrAlMilh.extent = {'xmax': 44.48, 'xmin': 43.13, 'ymax': 32.86, 'ymin': 32.4, 'spatialReference': 4326}
bahrAlMilh